add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$package\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold cyan"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"

[nodejs]
symbol = " "
style = "bold green"

[cmd_duration]
min_time = 2000
style = "dimmed white"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
